---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lihelyci/appone
    - mkdir -p $DEPLOYPATH
    - rsync -avz --exclude '.git' --exclude 'node_modules' --exclude 'tests' --exclude '.env' ./ $DEPLOYPATH
    # Uncomment the lines below if composer and php are available on your cPanel shell path
    # and you want to automate dependencies & optimizations:
    # - composer install --no-dev --optimize-autoloader --no-interaction
    # - php artisan migrate --force
    # - php artisan optimize
    # - php artisan storage:link
